### ISSUE TITLE
Charts and graphs

### ISSUE THREAD

**Issue by chrisco484** [alanhay/html-exporter#28]
Looks like a great library - I could have done with something like these 5 years ago when I had to generate some reports in Excel - ended up using raw POI back then but generating from HTML would have been a lot nicer.

Is there any way of inserting charts or graphs into an Excel file using html-exporter or do you have any hints as to how I might enhance html-exporter to support that?

**Comment by alanhay** [comment]
Hi. There is no direct way in the library. I _believe_ POI supports directly creating at least some charts now but haven't used it and don't know how extensive it is. 

Prior to this you could do charts by defining them in an Empty excel work book based on ranges and then populating the data using POI i.e. by loading and populating that existing workbook: POI maintains any existing charts, VBA code etc. in that workbook. I have used that approach (a long time ago) and it worked as advertised.

I don't really see any way to export a chart from HTML to POI so that is probably the best option here. Create a workbook with some charts defined on some dynamic data range > use that workbook as a template i.e. modify html-exporter to load an existing workbook > populate it using html-exporter.

**Comment by chrisco484** [comment]
That's a good suggestion. I'll give that a go, thanks.

**Comment by chrisco484** [comment]
On another note:

I actually made a fork and merged in the changes on the fusionnx fork (because it adds support for specifying font sizes with 'pt' suffix etc., and I had a lot of existing external .css files I wanted to use that used 'pt' for font sizes.

However the main purpose of my fork was to add support for external .css files via <link .. > tags.

It seems to be working well for me. It works under a couple of constraints:

- only supports <link .. > tags in the<head> element - not such a hassle as that's where most people put them.
- does not support nested imports e.g. importing a font file from with an external .css file but I think they aren't supported by html-exporter anyway no not such as problem

The core addition is the IResourceLoader interface which the user must supply an implementation for.

The changes are in this commit:

https://github.com/chrisco484/html-exporter/commit/3249e844d2b5796810ea06e6a50f0b9d4670af3c

I can raise a pull request if you like but it's going to include the changes from the fusionnx fork if that's ok.

**Comment by alanhay** [comment]
Hi. Yes, sounds useful. Feel free to raise a PR and I will review it when I have a minute.

Thanks.

Alan
